SELECT CONTACT_TYPE AS ContactType, NAME AS ContactName, EMAIL_ADDRESS AS ContactEmail FROM DEALER_ADDL_CONTACTS
WHERE UPPER(TRIM(DEALER_ID))=UPPER(TRIM(:DealerId)) AND COUNTRY_CODE=:CountryCode AND MAKE_CODE=:MakeCode 
