SELECT DISTINCT DN.COUNTRY_CODE AS CountryCode,
		M.MAKE_CODE AS MakeCode,
		M.MAKE_DESCRIPTION AS Make,
		DN.DEALER_ID AS DealerId,
		VENDOR_ID AS VendorId,
		VENDOR_NAME AS VendorName,
		CITY,STATE,ZIP_CODE AS ZipCode,
		SELLING_DELIV_IND AS SellingDelivInd,
		DEALER_RATING AS DealerRating,
		DEALER_COMMENTS AS DealerComments
FROM DEALER_NETWORK DN
INNER JOIN MAKE M on M.MAKE_CODE=DN.MAKE_CODE AND M.COUNTRY_CODE = DN.COUNTRY_CODE
WHERE (:CountryCode IS NULL OR DN.COUNTRY_CODE=:CountryCode)
	AND (:MakeCode IS NULL OR DN.MAKE_CODE= :MakeCode)
	AND (UPPER(TRIM(:DealerId)) IS NULL OR UPPER(TRIM(DN.DEALER_ID))= UPPER(TRIM(:DealerId)))
	AND (UPPER(TRIM(:VendorName)) IS NULL OR UPPER(TRIM(VENDOR_NAME)) LIKE UPPER(TRIM('%'||:VendorName||'%')))